site_name: ztalib
nav:
  - Getting Started: index.md
  - Reference:
      - reference/ztaf.md
      - reference/palf.md
  - Examples: examples.md
  - Contributing: contributing.md
theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: amber
